name: Build Docker Images

on:
  push:
    branches:
      - docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2
        with:
          docker-version: '20.10.7'  # Specify the Docker version you want to install

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build
